#!/bin/bash -e
#  Apt installer helper for Docker images

ARGS="$*"
echo "Installing $ARGS"

if [ -n "$(command -v yum)" ]; then
    echo "using yum"
    yum -y install $ARGS && yum -y clean all  && rm -rf /var/cache
fi

if [ -n "$(command -v apt-get)" ]; then
    echo "using apt"
    apt-get -q update && apt-get -qy install $ARGS \
        && apt-get -qy autoremove \
        && apt-get clean
fi